### ISSUE TITLE
Request - Chat Pins Viewable to Players

### ISSUE THREAD

**Issue by SoundSherpa** [DFreds/dfreds-chat-pins#1]
Great idea for a mod! Is it possible to have my players be able to see the pins as well? I want them or I to be able to pin certain things that may need to be rolled again or checked later. Currently, I cant easily refer them to the pinned chat card so they can reroll on it. 
Thanks!

**Comment by DFreds** [comment]
Yes! I am aware of this issue and it is coming in the next update

**Comment by DFreds** [comment]
Added in v1.1.0
