### ISSUE TITLE
Pinned Messages shown Twice after delete

### ISSUE THREAD

**Issue by jocolamarco** [DFreds/dfreds-chat-pins#2]
**Describe the bug**
Had a message pinned.
Player logged in and sent to chat various rolls
I pinned one of the new messages
Click to delete all
The only 2 pinned messages are shown twice,

**To Reproduce**
See above.

**Expected behavior**
The opposite of what happened (no duplication)

**Screenshots**
![image](https://user-images.githubusercontent.com/45291719/164894631-f8cdd494-7014-4c32-a56e-05d6aa18d959.png)

**Additional context**
No error messages logged.
**Pressing F5 to refresh the page fixes the issue.**

**Comment by DFreds** [comment]
Sorry for the slow response, but I'm unable to reproduce this :/
