### ISSUE TITLE
Allow players to pin messages

### ISSUE THREAD

**Issue by andriusch** [DFreds/dfreds-chat-pins#5]
**Is your feature request related to a problem? Please describe.**
Sometimes players want to pin their messages so that others can reference them easier on their turns. It seems that's not possible now and only GM can pin the messages.

**Describe the solution you'd like**
Player can right click a message and pin it, same as GM.

**Comment by DFreds** [comment]
I don't think this is possible without adding the socketlib library. Foundry doesn't allow manipulation of the chat data unless you are an assistant or GM, and the configuration of those permissions aren't available. I don't think I want to add socketlib just for this one feature... Perhaps if another use case arises, I'll consider it again.
